import {
  LayoutGrid, FolderKanban, FolderPlus, SquareCheck, CalendarDays, Calendar,
  Tag, Upload, Download, Settings, Search, Plus, X, Check, Pencil, Trash2, Copy,
  RotateCcw, Clock, AlarmClockPlus, Play, Pause, Square, Target, Sparkles,
  TrendingUp, CircleCheck, CircleAlert, TriangleAlert, Info, Bell, BellRing, Sun, Moon,
  Eye, EyeOff, LogIn, LogOut, ChevronLeft, ChevronRight, ArrowLeft, Eraser,
  FileJson, FileText, Save, Flag, LoaderCircle,
} from 'lucide-angular';

export const APP_ICONS: Record<string, typeof LayoutGrid> = {
  'layout-grid': LayoutGrid,
  'folder-kanban': FolderKanban,
  'folder-plus': FolderPlus,
  'square-check': SquareCheck,
  'calendar-days': CalendarDays,
  'calendar': Calendar,
  'tag': Tag,
  'upload': Upload,
  'download': Download,
  'settings': Settings,
  'search': Search,
  'plus': Plus,
  'x': X,
  'check': Check,
  'pencil': Pencil,
  'trash-2': Trash2,
  'copy': Copy,
  'rotate-ccw': RotateCcw,
  'clock': Clock,
  'alarm-clock-plus': AlarmClockPlus,
  'play': Play,
  'pause': Pause,
  'square': Square,
  'target': Target,
  'sparkles': Sparkles,
  'trending-up': TrendingUp,
  'circle-check': CircleCheck,
  'circle-alert': CircleAlert,
  'triangle-alert': TriangleAlert,
  'info': Info,
  'bell': Bell,
  'bell-ring': BellRing,
  'sun': Sun,
  'moon': Moon,
  'eye': Eye,
  'eye-off': EyeOff,
  'log-in': LogIn,
  'log-out': LogOut,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-left': ArrowLeft,
  'eraser': Eraser,
  'file-json': FileJson,
  'file-text': FileText,
  'save': Save,
  'flag': Flag,
  'loader-circle': LoaderCircle,
};
